     - name: "Common | Some common software should be installed"
       action: apt pkg=$item state=latest
       with_items:
          - facter
          - vim 
          - sudo
          - locales
          - locate
          - telnet
          - openssh-server
          - ssh
          - exim4
          - tar
          - bzip2
          - htop
          - screen
          - tree
       tags: common  

     - name: "Common | All your base are belong to ansible"
       action: copy src=templates/motd_ansible.j2 dest=/etc/motd mode=0755
       tags: common

     - name: "Common | Set the timezone"
       action: command /bin/echo ${timezone} > /etc/timezone  && command dpkg-reconfigure -f noninteractive tzdata
       tags: common

     - name: "Common | Use ssh keys"
       authorized_key: user=stephan key='$FILE(~/.ssh/id_rsa.pub)'
       tags: common